services:
  ui_backend:
    build: ./UI
    container_name: ui_backend
    ports:
      - "5002:5002"
    environment:
      - AI_BACKEND_URL=http://ai_backend:5001
    depends_on:
      - ai_backend

  ai_backend:
    build: ./AI
    container_name: ai_backend
    ports:
      - "5001:5001"